disk-mirror:
  # 此配置项目代表的就是是否启用 diskMirror 如果设置为 false 则代表不启用，diskMirror 的starter 将不会被加载
  enabled-feature: true
  # 要使用的盘镜适配器类型 在这里默认数值是本地盘镜适配器，具体的适配器 您可以查阅 top.lingyuzhao.diskMirror.core.DiskMirror 类
  adapter-type: "LocalFSAdapter"
  # 要被盘镜管理的目录 用于存储数据的目录 此目录是真实目录
  root-dir: "/DiskMirror"
  # 一般来说 如果对接带第三方文件系统 而非本次文件系统 则此参数则会派上用场，其代表的就是第三方文件系统的地址
  fs-default-fs: "hdfs://localhost:8020/"
  # 当处理之后，如果处理无错误会返回一个结果状态，此数值代表的就是是否正确处理
  ok-value: "ok!!!!"
  # 返回结果的key 返回结果中 结果状态的字段名字
  res-key: "res"
  # 协议前缀，默认为http 不同协议前缀有不同的意义，用于拼接 url
  protocol-prefix: "http://localhost:80/"
  # 参数 可能会派上用场，在不同的适配器中有不同的实现
  params: { }
  # 用户磁盘配额 每个盘镜空间的磁盘最大空间数值，单位是字节
  user-disk-mirror-space-quota: 134217728
  # 安全密钥
  secure-key: ""
  # 指定的几个用户的空间对应的容量
  space-max-size: { }
  # 指定后端服务器相关的配置
  backend:
    # 指定后端服务器的关机控制器
    shutdown-controller:
      # 这里代表是否要启用关机控制器
      enable: false
      # 这里代表的是关机控制器的操作密钥 此密钥独立于 diskMirror 可防止被其它用户关机
      password: "zhao"
      # 这里代表的是在关机之前预留的时间，一般是用来将关机的信息返回给客户端的 单位是毫秒
      timeout: 5000
  # 设置要使用的空间配置方式 目前支持 HashMapper 和 JedisMapper 两种，用于将不同空间的配置信息放到第三方平台
  use-space-config-mode: "HashMapper"
  # redis 配置
  redis-host-port-db: "127.0.0.1:6379:0"
  # redis 密码
  redis-password: "0000"
  # 图像文件压缩模块配置
  image-compress-module:
    # 设置位 true 代表启用~ 反之则不启用 不启用的将不会被加载到 diskMirror 中
    enable: false
    # 设置 png 调色板模式 默认是 RGB_8 代表 8 位压缩
    palette-png: "RGB_8"
    # 设置 调色板生成器，默认是 X255
    palette-generator: "X255"
    # 设置是否支持透明 默认是 false
    transparent: false
  # 设置校验模块
  verifications:
    # 设置读取操作中的 sk 校验 这样所有的读取操作都需要经过这个模块了
    - "SkCheckModule$read"
    # 设置写入操作中的 sk 校验 这样所有的写入操作都需要经过这个模块了
    - "SkCheckModule$writer"

# Spring Boot 配置文件
spring:
  # mvc 配置
  mvc:
    resources:
      cache:
        # 设置缓存时间 这里是以秒为单位 代表的 1 小时
        period: 3600
        # cachecontrol 具有更多的配置，其中也包括 period 但是叫做 max-age 并且 通过 cachecontrol 配置的优先级更高
        # 也就是说 在这里配置最后会直接覆盖掉 cache.period
        # 一般来说 需要更详细的配置就需要在这里操作
        cachecontrol:
          # 设置缓存的过期时间 这是告诉浏览器此资源缓存 7200 秒
          max-age: 7200
        # 配置资源的对比策略，这里是使用的最后一次修改的时间
        # 这个配置项在 spring 5.2.0 之后才支持
        # 如果不配置此选项 默认的策略是 Last-Modified
        # Last-Modified 的策略是根据资源的最后修改时间来判断资源是否被修改过
        # 如果资源被修改过 则会返回 304 状态码
        # 如果资源没有被修改过 则会返回 200 状态码
        # 但是 Last-Modified 的策略存在一个问题，就是如果资源的最后修改时间被修改过，那么资源的最后修改时间也会被修改，这样就会导致资源的最后修改时间永远是当前时间。
        # 这个配置项默认是 true
        use-last-modified: true
  # 配置 HTTP 多部分文件上传
  servlet:
    # 文件上传相关配置
    multipart:
      # 指定临时文件的存储位置
      # 注意：此目录必须存在，并且应用程序应具有写入权限
      location: /opt/app/diskMirror-spring-boot/temp
      # 指定临时文件的位置（与location配置相同）
      # 这个配置在较新版本的Spring中可能不是必需的
      # temp-location: /opt/app/diskMirror-spring-boot/temp
      # 单个文件的最大大小
      max-file-size: 1024MB
      # 整个请求中所有文件的总大小的最大值，默认值为多部分数据的最大大小
      max-request-size: 1030MB
      # 是否启用文件大小检查，默认为true
      enabled: true
      # 当文件大小超过这个阈值时，才会使用临时文件存储
      file-size-threshold: 4MB